### PR TITLE
Fix dashboard for our metrics

### PR DESCRIPTION
**Pull request by gravelg**
* cluster -> k8s_cluster
* Fix `job` pattern

### CODE REVIEW

**Comment by gravelg** [comment]
I'll fix the mixins properly tomorrow

**Comment by rdooley** [comment]
> Is it possible to make `k8s_cluster` a variable? 
(yes)

> Maybe we could upstream this. I guess the `job` field would be a problem though. IIRC that job field lines up with how the prometheus-operator jobs are setup

That's just the crawl job that prometheus or prometheus-agent use in the crawl config iirc (should be upstreamable)

**Comment by gravelg** [comment]
> That's just the crawl job that prometheus or prometheus-agent use in the crawl config iirc (should be upstreamable)
Do you mean to our prometheus configuration?

**Comment by rdooley** [comment]
> > That's just the crawl job that prometheus or prometheus-agent use in the crawl config iirc (should be upstreamable)
> 
> Do you mean to our prometheus configuration?

I no longer remember what I meant, but it wasn't this

**Review by rdooley — APPROVED** [review]
seems like the key change

**Pull request merged**
